[package]
name = "neoroll_world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
strum_macros = "0.25.2"
weighted_rand = "0.4"
# tests
rstest = "0.18.1"